project:
  type: website
  output-dir: _site

website:
  title: "Formation QGIS"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Accueil
      - href: ressources/telechargements.qmd
        text: Téléchargements
      - section: "Introduction à QGIS"
        contents:
          - href: introduction-qgis/introduction-qgis.qmd
            text: "Présentation du module"
          - href: introduction-qgis/interface-et-projet.qmd
            text: "Interface et projet QGIS"
          - href: introduction-qgis/donnees-et-couches.qmd
            text: "Données et gestion des couches"
          - href: introduction-qgis/interrogation-symbologie.qmd
            text: "Interrogation, sélection et symbologie"
          - href: introduction-qgis/edition-export-mise-en-page.qmd
            text: "Édition, export et mise en page"
          - href: introduction-qgis/formulaires-signets-3d.qmd
            text: "Formulaires, signets et introduction 3D"
      - section: "Base de données et projet QGIS"
        contents:
          - href: base-de-donnees/prerequis-logiciels-bd.qmd
            text: "Prérequis logiciels PostgreSQL / PostGIS"
          - href: base-de-donnees/modelisation-base-de-donnees.qmd
            text: "Modélisation de base de données"
          - href: base-de-donnees/implementation-base-gpkg.qmd
            text: "Implémentation d’une base de données GPKG"
          - href: base-de-donnees/configuration-projet-qgis.qmd
            text: "Configuration du projet QGIS"
          - href: base-de-donnees/introduction-postgresql-postgis.qmd
            text: "Introduction à PostgreSQL / PostGIS"
          - href: base-de-donnees/introduction-interlis.qmd
            text: "Introduction à Interlis"
      - section: "QField"
        contents:
          - href: qfield/export-projet-qfieldcloud.qmd
            text: "Export d’un projet QGIS pour QFieldSync"
          - href: qfield/leve-et-edition-qfield.qmd
            text: "Levé et édition QField"
      - section: "Advanced QGIS"
        contents:
          - section: "Édition avancée"
            contents:
              - href: advanced-qgis/numerisation-avancee.qmd
                text: "Numérisation avancée"
              - href: advanced-qgis/edition-topologique.qmd
                text: "Édition topologique"
          - section: "Expressions QGIS"
            contents:
              - href: advanced-qgis/expressions-qgis.qmd
                text: "Expressions QGIS"
          - section: "Géotraitement"
            contents:
              - href: advanced-qgis/boite-outils-geotraitement.qmd
                text: "Boîte à outils de géotraitement"
              - href: advanced-qgis/automatisation-flux-geotraitement.qmd
                text: "Automatisation de flux de géotraitement"
              - href: advanced-qgis/modeleur-flux-kde.qmd
                text: "Modéleur graphique : flux KDE"
              - href: advanced-qgis/introduction-plugins-qgis.qmd
                text: "Introduction aux plugins QGIS"
      - section: "Développement avancé QGIS"
        contents:
          - href: developpement-avance/introduction-developpement.qmd
            text: "Introduction au développement"
          - href: developpement-avance/traitement-kde.qmd
            text: "Traitement personnalisé KDE"
          - href: developpement-avance/plugin-kde.qmd
            text: "Plugin QGIS KDE"

format:
  html:
    theme: cosmo
    toc: true

lang: fr
