---
title: "Introduction à Interlis"
subtitle: "Module 1 : Standard de modélisation suisse et déploiement local"
format:
  html:
    toc: true
    number-sections: true
    code-fold: true
---

## Introduction

Jusqu'ici, nous avons construit et exploité des bases de données en **GPKG** puis en **PostgreSQL/PostGIS**. Interlis ajoute une couche essentielle : la **normalisation du modèle de données**.

Autrement dit :

* GPKG / PostGIS répondent à la question « **où stocker** les données ? »
* Interlis définit:
  * **comment structurer** les données de façon cohérente et dans le respect d'un modèle défini
  * **comment échanger** les données entre systèmes en garantissant leur compatibilité avec le modèle.

Le but de ce chapitre est d'être capable de déchiffrer et comprendre un modèle Interlis, et de le déployer localement dans un GPKG avec le plugin Model Baker.

---

## Interlis dans le contexte des bases de données

### À quoi sert Interlis ?

Interlis est un standard suisse de modélisation et d'échange de données géographiques **indépendant du système de stockage**. Il permet aux organisations la liberté de choisir leur technologie d'implémentation (GPKG, PostGIS, etc.) tout en contraignant le format d'échange.

Dans un projet SIG, Interlis sert à :

* définir un **modèle de données explicite** (classes, attributs, relations, domaines),
* imposer des **règles de qualité** (cardinalités, types, contraintes),
* "faciliter" (ou plutôt normaliser) l'**échange entre systèmes** (administrations, bureaux, prestataires),
* garder la même logique métier, quel que soit le stockage final (GPKG, PostGIS, etc.).

### Lien avec ce qui a été vu avant

* Avec le GPKG, nous avons vu une structure simple et locale.
* Avec PostGIS, nous avons ajouté robustesse, multi-utilisateur et gouvernance.
* Avec Interlis, nous ajoutons la **standardisation du modèle** et la **portabilité métier**.

Interlis ne remplace pas PostGIS ou GPKG : il les complète en définissant une structure métier normative.

### Concepts clés à retenir

* **Modèle (`.ili`)** : description formelle des objets métier.
* **Transfert** : import/export de données conformes au modèle via des fichiers `.xtf` (format XML).
* **Validation** : contrôle de conformité des données par rapport au modèle et ses contraintes.

### Schéma d'architecture

```{mermaid}
flowchart LR
  A[Modele Interlis .ili] --> B[Creation de la base GPKG ou PostGIS]
  B --> C[Saisie et edition des donnees]
  C --> D[Export Interlis .xtf]
  A --> E[Validation avec ilivalidator]
    D --> E
  E --> F[Livraison du XTF valide]
```

---

## Analyse d'un modèle

Pour cet exercice, nous prenons un exemple d'un MGDM existant :

* **Cadastre des sites pollués : KbS_V1_5** (Kataster der belasteten Standorte)

> Modèle officiel BAFU disponible à : [https://models.geo.admin.ch/BAFU/](https://models.geo.admin.ch/BAFU/)
>
> Documentation : [https://www.bafu.admin.ch/geodatenmodelle](https://www.bafu.admin.ch/geodatenmodelle)
>
> Version analysée : **KbS_V1_5** (2021-10-15)



### Ce qu'il faut observer dans le modèle

Lors de l'analyse du modèle Interlis, identifiez :

* les **import** d'autres modèles (réutilisation de structures communes),
* les **domains** (valeurs autorisées),
* les **structure**: types de données et géométrie custom ,
* les **topic**: thèmes principaux du modèle,
* les **class** (objets métier),
* les **association** (liens entre objets),
* les **constraint** (règles de validité).
   

#### Exemple de classe
Une classe représente un objet métier avec des attributs et une géométrie. Certains attributs ont des types personnalisés (ex: `StatusAltlV`), d'autres sont des types de base (ex: `TEXT`, `INTERLIS.XMLDate`).

Il convient de trouver dans le modèle interlis les classes principales (souvent au fond du fichier après toutes les définitions des dépendances) ici: 

* `Belasteter_Standort` (site pollué)
* `ZustaendigkeitKataster` (autorité responsable du site) 
  
```ili
CLASS Belasteter_Standort = 
    Katasternummer : MANDATORY TEXT;
    URL_Standort : MultilingualUri;
    Geo_Lage_Polygon : MultiPolygon;
    Geo_Lage_Punkt : GeometryCHLV95_V1.Coord2;
    Parzellenverweis : BAG {0..*} OF KbS_V1_5.Parzellenidentifikation;
    EGRID : BAG {0..*} OF KbS_V1_5.EGRID_;
    Standorttyp : MANDATORY KbS_V1_5.Standorttyp;
  ...
END Belasteter_Standort;  
```
Lecture : `Belasteter_Standort` est une classe avec des attributs textuels, des dates et deux géométries (polygone et point). 

```{mermaid}
erDiagram
    "KbS_V1_5.ZustaendigkeitKataster" {
        text Zustaendige_Behoerde
        string URL_Behoerde
        string UID
        text Katastername
        string URL_Kataster
    }

    "KbS_V1_5.Belasteter_Standort" {
        text Katasternummer PK
        string URL_Standort
        geometry Geo_Lage_Polygon
        geometry Geo_Lage_Punkt
        text Standorttyp
        text StatusAltlV
        date Ersteintrag
        date LetzteAnpassung
    }

    "KbS_V1_5.ZustaendigkeitKataster" ||--o{ "KbS_V1_5.Belasteter_Standort" : "gère"
```


#### Exemple de type d'attributs personnalisés (domain, class et structure)

`Standorttyp` est un type d'attribut personnalisé, défini plus haut dans le modèle.

```ili
  DOMAIN

    Standorttyp = (
      StaoTyp1,
      StaoTyp2,
      StaoTyp3,
      StaoTyp4
    );

  TOPIC Codelisten =
    CLASS Standorttyp_Definition =
      Code : MANDATORY KbS_V1_5.Standorttyp;
      Definition : MANDATORY LocalisationCH_V1.MultilingualText;
      UNIQUE Code;
    END Standorttyp_Definition;
 END Codelisten;
```
Lecture : `Standorttyp` est un domaine avec 4 valeurs possibles. La classe `Standorttyp_Definition` permet de documenter ces codes avec une définition multilingue.

`Parzellenidentifikation` est une structure personnalisée, définie dans un autre modèle importé qui contient des champs spécifiques pour identifier une parcelle cadastrale.

```ili
  STRUCTURE Parzellenidentifikation =
    NBIdent : MANDATORY TEXT;
    Parzellennummer : MANDATORY TEXT;
  END Parzellenidentifikation;
```
Lecture : `Parzellenidentifikation` est une structure avec deux champs textuels, utilisée pour référencer des parcelles cadastrales.

#### Exemple de contrainte

Les contraintes empêchent les incohérences.

```ili
    CLASS Belasteter_Standort =
      Katasternummer : MANDATORY TEXT;
      ...
      !!!@ Si Standorttyp vaut #StaoTyp1, alors InBetrieb doit être renseigné.
      MANDATORY CONSTRAINT NOT ((Standorttyp == #StaoTyp1) AND NOT (DEFINED (InBetrieb)));
      !!!@ Si le type de site est StaoTyp1 et que le site est en exploitation (InBetrieb = TRUE), alors Deponietyp doit être renseigné.
      MANDATORY CONSTRAINT NOT ((Standorttyp == #StaoTyp1) AND (InBetrieb) AND NOT (DEFINED (Deponietyp)));
      !!!@ Au moins une des deux géométries doit être renseignée.
      MANDATORY CONSTRAINT DEFINED (Geo_Lage_Punkt) OR DEFINED (Geo_Lage_Polygon);
      ...
END Belasteter_Standort;
```
Lecture : ces trois contraintes assurent que les données respectent des règles métier spécifiques, par exemple que certains champs soient renseignés selon le type de site ou que l'une des géométries soit toujours présente.


#### Exemple de relation

Le modèle relie les sites (`Belasteter_Standort`) à l'autorité responsable (`ZustaendigkeitKataster`) avec une logique 1:N.

```ili
    ASSOCIATION ZustaendigkeitKatasterBelasteter_Standort =
      ZustaendigkeitKataster -- {1} ZustaendigkeitKataster;
      Belasteter_Standort -<> {0..*} Belasteter_Standort;
    END ZustaendigkeitKatasterBelasteter_Standort;
```

Lecture : chaque site doit référencer une autorité, et une autorité peut être liée à plusieurs sites.

#### Les imports : réutilisation de modèles standards

En haut du fichier `.ili` du modèle KbS_V1_5, vous verrez :

```ili
INTERLIS 2.3;

MODEL KbS_V1_5 (de)
AT "https://models.geo.admin.ch/BAFU/"
VERSION "2021-10-15"  =
  IMPORTS LocalisationCH_V1,GeometryCHLV95_V1,InternationalCodes_V1;
```

Ces lignes **importent d'autres modèles standardisés** pour réutiliser des structures communes :

* **LocalisationCH_V1** : adresses, communes, cantons suisses, textes multilingues.
* **GeometryCHLV95_V1** : types géométriques en coordonnées suisses (EPSG:2056, `Coord2`).
* **InternationalCodes_V1** : codes ISO internationaux (langues, etc.).

Cela illustre un principe clé d'Interlis : **réutiliser plutôt que redéfinir**. C'est gagner en cohérence, en maintenance et en facilité d'échange entre projets.


---

## Mise en place locale avec le plugin Model Baker (sortie GPKG)

Objectif : générer localement une structure de base de données à partir du modèle Interlis, sans serveur, dans un fichier GeoPackage.

### Pré-requis

* QGIS installé.
* Plugin **Model Baker** installé dans QGIS.
* Java disponible (requis par `ili2db`, utilisé en arrière-plan par Model Baker).

### Installer Model Baker dans QGIS

1. Ouvrez **Extensions > Installer/Gérer les extensions**.
2. Recherchez **Model Baker**.
3. Installez le plugin puis redémarrez QGIS si nécessaire.

### Import du modèle Interlis en GPKG et configuration du projet

1. Ouvrez l'interface Model Baker.
2. Cliquer sur " Choisir les fichiers de données et les modèles à importer ou générer une nouvelle base de données".
3. Choisir le fichier `.ili` du modèle à importer (ex. `KbS_V1_5.ili`).
4. Type de base : **GeoPackage**.
5. Créez un fichier cible, par exemple `KbS.gpkg`.
6. Sélectionnez le modèle environnemental choisi (ex. KbS).
7. Créér les conteneurs de données (topics) et les classes à importer.
8. Ne pas importer de données (on a pas de fichier `.xtf` d'exemple pour ce modèle).
9. Générer le projet QGIS


Résultat attendu :

* tables principales déjà structurées,
* domaines/lists de valeurs disponibles,
* relations prêtes à l'emploi pour les formulaires.

---

<!-- ## 4. Exercice guidé

1. Ouvrir le registre des modèles de données de la Confédération.
2. Identifier un modèle environnemental simple (ex. KbS).
3. Lister 3 domaines de valeurs utiles à la saisie.
4. Générer le modèle avec Model Baker dans un GPKG local.
5. Vérifier dans QGIS qu'un formulaire d'édition propose bien des valeurs contrôlées.

::: {.callout-note}
## Point d'attention

Model Baker automatise la création de structure, mais la réussite dépend de trois éléments :

* bon dépôt de modèles,
* version correcte du modèle,
* environnement Java fonctionnel.
:::

--- -->

## Conclusion

Interlis complète parfaitement GPKG et PostGIS :

* il formalise le modèle,
* il sécurise l'échange,
* il améliore la qualité des données.

Avec Model Baker, vous pouvez déployer rapidement ce modèle en local (GPKG), puis évoluer ensuite vers PostGIS en conservant la même logique métier.

Model Baker permet de répondre aux besoins courants Interlis dans un environnement Open Source.

## Références

* Registre des modèles de données : [https://www.geo.admin.ch/fr/registre-des-modeles-de-donnees](https://www.geo.admin.ch/fr/registre-des-modeles-de-donnees)
* Documentation Model Baker : [https://opengisch.github.io/project/modelbaker/](https://opengisch.github.io/project/modelbaker/)
* Dépôt de modèles Interlis : [https://models.interlis.ch/](https://models.interlis.ch/)


## Logiciels
* Voir page de pré-requis logiciels : [https://formation-qgis.fr/base-de-donnees/prerequis-logiciels-bd/](https://formation-qgis.fr/base-de-donnees/prerequis-logiciels-bd/)
