---
title: "Téléchargements"
---

Cette page regroupe les fichiers utiles par module.

## Navigation par dossiers ressources

Vous pouvez naviguer par dossiers depuis ces liens :

- [Dossier Introduction QGIS](fichiers/introduction-qgis/)
- [Dossier Base de données](fichiers/base-de-donnees/)
- [Dossier Géotraitements](fichiers/geotraitements/)
- [Dossier Numérisation avancée](fichiers/numerisation-avancee/)

> Selon l'hébergement, l'affichage direct du contenu d'un dossier peut être limité.
> Dans ce cas, utilisez les liens de fichiers ci-dessous.

## Introduction à QGIS

- [Diaporama de la formation](fichiers/introduction-qgis/formation_qgis.pptx){download="formation_qgis.pptx"}
- [Pack d'exercices](fichiers/introduction-qgis/Exercices_formation.zip){download="Exercices_formation.zip"}
- [Template QGIS géoservices](fichiers/introduction-qgis/templates_qgis/template_geoservices.qgz){download="template_geoservices.qgz"}
- [Template QGIS mise en page](fichiers/introduction-qgis/templates_qgis/template_mise_en_page.qgz){download="template_mise_en_page.qgz"}
- [Mise en page A4 paysage](fichiers/introduction-qgis/mises_en_page/a4_paysage.qpt){download="a4_paysage.qpt"}
- [Mise en page A4 portrait](fichiers/introduction-qgis/mises_en_page/a4_portrait.qpt){download="a4_portrait.qpt"}
- [Mise en page A3 paysage](fichiers/introduction-qgis/mises_en_page/a3_paysage.qpt){download="a3_paysage.qpt"}
- [Mise en page A3 portrait](fichiers/introduction-qgis/mises_en_page/a3_portrait.qpt){download="a3_portrait.qpt"}


## Base de données

- [Tables biodiversité sans attributs pour ajout via SQL](fichiers/base-de-donnees/biodiversite_tables_vides.gpkg){download="biodiversite_tables_vides.gpkg"}
- [Tables biodiversité avec attributs](fichiers/base-de-donnees/biodiversite_tables_et_attributs.gpkg){download="biodiversite_tables_et_attributs.gpkg"}
- [GPKG biodiversité avec données](fichiers/base-de-donnees/biodiversite_data.gpkg){download="biodiversite_data.gpkg"}
- [Projet QGIS biodiversité (QGS)](fichiers/base-de-donnees/biodiversite.qgs){download="biodiversite.qgs"}
- [Script SQL non spatial (DB Browser)](fichiers/base-de-donnees/01_donnees_biodiv_enrichies_non_spatial_dbbrowser.sql){download="01_donnees_biodiv_enrichies_non_spatial_dbbrowser.sql"}
- [Script SQL spatial (QGIS)](fichiers/base-de-donnees/02_donnees_biodiv_enrichies_spatial_qgis.sql){download="02_donnees_biodiv_enrichies_spatial_qgis.sql"}
- [Modèle interlis KbS](fichiers/base-de-donnees/KbS_V1_5.ili){download="KbS_V1_5.ili"}

## QField

Pas de fichiers.

## Advanced QGIS

- [GeoPackage numérisation avancée](fichiers/numerisation-avancee/advanced_digitalisation.gpkg){download="advanced_digitalisation.gpkg"}
- [Script SQL génération du GeoPackage de numérisation avancée](fichiers/numerisation-avancee/generate_advanced_digitalisation_gpkg.sql){download="generate_advanced_digitalisation_gpkg.sql"}
- [README numérisation avancée](fichiers/numerisation-avancee/README.md){download="README_numerisation-avancee.md"}

### Géotraitements (modeleur)

- [Solution modeleur - calcul des statistiques](fichiers/geotraitements/01_compute_stats.model3){download="01_compute_stats.model3"}
- [Solution modeleur - génération de contours](fichiers/geotraitements/02_contours.model3){download="02_contours.model3"}
